<a href="https://colab.research.google.com/github/GabrielMariz/GabrielMariz/blob/main/Pratica1NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

##Criando uma Lista


In [7]:
minhaLista=[0,1,2,3,4,5,6,7,8]
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

##Transformando a lista em array NumPy


In [9]:
meuArray = np.array (minhaLista)
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

##Printando na tela

In [10]:
print(meuArray)

[0 1 2 3 4 5 6 7 8]


## Forma mais simples de lista com range

In [11]:
minhaLista = list(range(9))
print(minhaLista)

[0, 1, 2, 3, 4, 5, 6, 7, 8]


##Transformando a lista num aray de forma mais simples

In [12]:
meuArray2 = np.arange(9)
print(meuArray2)

[0 1 2 3 4 5 6 7 8]


##Star, Stop, Step

In [15]:
array3 = np.arange(0,10,0.5)
print(array3)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


##Arredondando os valores Obtidos no arra3

In [16]:
roundArray3 = np.around(array3)
print(roundArray3)

[ 0.  0.  1.  2.  2.  2.  3.  4.  4.  4.  5.  6.  6.  6.  7.  8.  8.  8.
  9. 10.]


##Fornçando os tipos

In [23]:
array3 = np.arange(0,10,0.5, dtype = int)
print(array3)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


##Pré determinando os tipos

In [32]:
array4 = np.arange(12)
array4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

##Preparando meu array para tipo float

In [33]:
array4= np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

##Verificando o tipo do objeto

In [34]:
type(array4)

numpy.ndarray

##Verificando o tipo dos elementos do array

In [35]:
array4.dtype

dtype('float64')

##array digiando os valores

In [36]:
vetor1 = np.array([0,1,2,3,4])
print(vetor1)

[0 1 2 3 4]


##Selecionando um elemento específico

In [40]:
vetor1[3]

3

##Selecionando um intervalo específico

In [38]:
vetor1[0:2]

array([0, 1])

##Criando um array de String

In [42]:
s= np.array(['Python', 'Profissional', 'java', "Água"] )
s


array(['Python', 'Profissional', 'java', 'Água'], dtype='<U12')

In [44]:
s=np.array(['Python]',12131325, 'Profissional','Java'])
s

array(['Python]', '12131325', 'Profissional', 'Java'], dtype='<U21')

##Alterando um elemento do Array

In [46]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

##Incluindo Elementos

In [48]:
vetor1[0] = 'Novo Elemento'
vetor1

ValueError: ignored

In [49]:
vetor1[0] = 45.6
vetor1

array([45,  1, 10,  3,  4])